baseURL: https://hemendrarajawat.in/
languageCode: en-us
title: Hemendra Singh Rajawat
theme: PaperMod
googleAnalytics: G-9VJ1M639JP

taxonomies:
    category: categories
    tag: tags

menu:
    main:
        - identifier: home
          name: Home
          url: /
          weight: 10
        - identifier: blog
          name: Blog
          url: /blog
          weight: 20
        - identifier: projects
          name: Projects
          url: /projects
          weight: 30
        - identifier: experience
          name: Experience
          url: /experience
          weight: 40
        - identifier: search
          name: Search
          url: /search
          weight: 50
        - name: Tags
          url: tags/
          weight: 60

params:
    defaultTheme: auto
    env: production
    description: Portfolio and blog website of Hemendra about tech, ai/ml, and projects.

    profileMode:
        enabled: true
        title: Hemendra Singh Rajawat
        subtitle: "
        **Salesforce & TensorFlow Certified Developer** \n

        Senior Consultant at Deloitte with 6+ years of development experience 💻. My hobby is cycling 🚴‍♂️. Checkout my projects too focused on machine learning.
        "
        imageUrl: home/me.jpg
        imageWidth: 220
        imageHeight: 220
        buttons:
            - name: ↓ Resume
              url: home/hemendra_resume.pdf

    socialIcons:
        - name: email
          url: mailto:hemendra.rajawat@outlook.com
        - name: linkedin
          url: https://www.linkedin.com/in/hsrajawat/
        - name: github
          url: https://github.com/hemendrarajawat
        - name: kaggle
          url: https://www.kaggle.com/hemendrasr

    ShowShareButtons: true
    ShowReadingTime: true
    ShowToc: true
    TocOpen: false
    ShowBreadCrumbs: true
    ShowPostNavLinks: true
    ShowCodeCopyButtons: true
    hideDescriptionInList: false

    cover:
        hidden: false
        linkFullImages: false
        hiddenInList: false
        hiddenInSingle: true

    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content", "description"]

outputs:
    home:
        - HTML
        - RSS
        - JSON

markup:
  goldmark:
    renderer:
      unsafe: true
